server:
  port: 9020

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testing?useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: pedro1234
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    showSql: true
    hibernate:
      ddlAuto: create-drop